service: devyard
image: devyard

servers:
  web:
    - 54.198.110.172

proxy:
  ssl: true
  host: devyard.co
  app_port: 3000

  healthcheck:
    path: /up
    interval: 3
    timeout: 30

ssh:
  user: ubuntu

registry:
  server: 748435451926.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE

volumes:
  - /data/devyard/storage:/rails/storage

builder:
  arch: amd64
  context: .
  dockerfile: Dockerfile

aliases:
  console: app exec -i 'bin/rails console'
  migrate: app exec 'bin/rails db:migrate'
  migrate-status: app exec 'bin/rails db:migrate:status'
  rollback-migration: app exec 'bin/rails db:rollback'
  logs: app logs -f
  bash: app exec -i 'bash'
  routes: app exec 'bin/rails routes'
  about: app exec 'bin/rails about'
  restart: app restart
  assets: app exec 'bin/rails assets:precompile'
  disk: app exec 'df -h'
  rake: app exec 'bin/rails'
